/* Auto-generated by tools/track_pipeline.py -- DO NOT EDIT BY HAND.
 * Regenerate after ANY track.geojson/loop_lengths.csv change. */
#ifndef TRACK_DATA_H
#define TRACK_DATA_H

#include "track_types.h"  /* track_point_t, track_segment_t */

#define TRACK_NUM_SEGMENTS 2
#define TRACK_NUM_LOOPS 1

static const char *const TRACK_LOOP_NAMES[TRACK_NUM_LOOPS] = {
    "dummy_loop",
};

static const track_point_t track_pts_0[8] = {
    { 13000000, 1038000000 },
    { 13000000, 1038000429 },
    { 13000000, 1038000857 },
    { 13000000, 1038001286 },
    { 13000000, 1038001714 },
    { 13000000, 1038002143 },
    { 13000000, 1038002571 },
    { 13000000, 1038003000 },
};
static const track_point_t track_pts_1[8] = {
    { 13000000, 1038003000 },
    { 13000000, 1038003429 },
    { 13000000, 1038003857 },
    { 13000000, 1038004286 },
    { 13000000, 1038004714 },
    { 13000000, 1038005143 },
    { 13000000, 1038005571 },
    { 13000000, 1038006000 },
};

static const track_segment_t TRACK_SEGMENTS[TRACK_NUM_SEGMENTS] = {
    { "DUMMY_A_B", "A", "B", 0, 1, 33000, 8, track_pts_0 },
    { "DUMMY_B_C", "B", "C", 0, 1, 34000, 8, track_pts_1 },
};

/* Reachable next segments, forward direction (this.to == next.from). */
static const int16_t TRACK_NEXT_FWD[TRACK_NUM_SEGMENTS][TRACK_NUM_SEGMENTS] = {
    { 1, -1 },
    { -1, -1 },
};
static const uint8_t TRACK_NEXT_FWD_COUNT[TRACK_NUM_SEGMENTS] = { 1, 0 };

#endif /* TRACK_DATA_H */
