/*
 * Stage 5 -- real GNSS (direct AT commands) + map matcher + optional
 * IMU stationary gate (Build Plan Sec 5 / TDD Sec 5.3-5.5).
 *
 * Serial + SD only in this harness -- no Wi-Fi/MQTT. Deferred per
 * explicit user instruction until a SIM card is available to test
 * cellular + MQTT together (Stage 7). Reuses Stage 6's SD
 * store-and-forward pattern: one fixed /lrv_log/ directory, appended
 * to across every boot (not a fresh folder per boot -- that was an
 * earlier design, dropped after it grew unboundedly across routine
 * test resets with no benefit).
 *
 * Core 0 runs two independent tasks, sampled at different rates on
 * purpose -- IMU state recognition needs to react within a few hundred
 * ms, GNSS is inherently a 1 Hz fix:
 *   - imu_task (IMU_ENABLED only): samples the MPU6050 at 20 Hz
 *     (IMU_SAMPLE_INTERVAL_MS) and updates a shared stationary/moving
 *     flag. This used to be piggybacked on gnss_matcher_task's own 1 Hz
 *     loop -- decoupled so the classifier gets a real decision window
 *     (imu_state.h's IMU_STATE_WINDOW_SAMPLES) instead of one sample
 *     per second, which was too coarse to recognise state changes
 *     promptly or reject vibration noise properly.
 *   - gnss_matcher_task: once per second, reads that flag -- if
 *     stationary, skips the GNSS poll entirely (saves modem cycles/
 *     power); otherwise issues a raw AT+CGNSSINFO query, parses it,
 *     and feeds the fix into the map matcher. Every valid fix is
 *     printed/logged to gnss_raw.ndjson on its own -- independent of
 *     the matcher -- so GNSS acquisition can be verified before
 *     trusting matcher output. A completed segment additionally goes
 *     on the queue for Core 1.
 * Core 1 (Arduino loop()): commit-before-publish (seq_store), Serial +
 *         SD logging of completed segments (events.ndjson), queue
 *         draining. No network I/O.
 *
 * Modem/GNSS is driven entirely by direct AT commands over SerialAT,
 * no TinyGSM -- explicit user request, and also the pragmatic choice:
 * the publicly published vshymanskyy/TinyGSM package has no SIM7670G
 * modem definition at all (confirmed by inspecting its source), so the
 * team's earlier reference sketch's `#define TINY_GSM_MODEM_SIM7670G`
 * only ever compiled against LilyGo's own vendored fork, never the
 * registry package PlatformIO actually resolves here. Every AT command
 * used (AT+CGNSSPWR, AT+CGNSSMODE, AT+CGNSSINFO) is confirmed against
 * SIMCOM's own SIM767XX Series_AT Command Manual_V1.06, but the CALL
 * ORDER in gnss_bringup() follows the reference sketch's own proven
 * structure (mode set once before power-on, not after) rather than the
 * manual's stated "CGNSSMODE is valid after GNSS power on" -- see
 * gnss_bringup()'s own comment for why.
 *
 * Known simplifications (flagged, not silent):
 *   - dir ('E'/'W') is a Stage 5 placeholder for forward/reverse
 *     traversal, not a real cardinal direction -- see map_matcher.h.
 *   - firmware/src/track_data.h currently holds a throwaway dummy
 *     dataset (track.dummy.geojson), not a real surveyed track --
 *     fine for testing GNSS/IMU visibility, not for matcher accuracy.
 *     Regenerate via tools/track_pipeline.py once real track data
 *     exists (Build Plan Sec 4 / README).
 *   - lat/lon are parsed as plain decimal degrees (gnss_parser.c), per
 *     the reference sketch's own hardware observation on this exact
 *     modem -- the AT manual's own printed CGNSSINFO example looks
 *     more like NMEA ddmm.mmmm instead, an unresolved conflict worth a
 *     sanity check against a known location on the very first real fix.
 */
#include <Arduino.h>
#include <Wire.h>

extern "C" {
#include "event_serializer.h"
#include "seq_store.h"
#include "gnss_parser.h"
#include "map_matcher.h"
#include "imu_state.h"
#include "imu_mpu6050.h"
}

#include <SPI.h>
#include <SD.h>

#include "../../config.h"
#include "../../pins_board.h"
#include "track_data.h" /* TRACK_SEGMENTS, TRACK_NUM_SEGMENTS, TRACK_NEXT_FWD(_COUNT) --
                          * generated by tools/track_pipeline.py, see header comment above */

#define SerialAT Serial1
#define SAMPLE_INTERVAL_MS 1000UL /* 1 Hz, TDD */
#define RAW_GPS_TIMEOUT_MS 800UL
#define IMU_SAMPLE_INTERVAL_MS 50UL /* 20 Hz -- decoupled from GNSS's 1 Hz, see imu_task */

/* Written only by imu_task, read only by gnss_matcher_task -- a single
 * bool is a single-instruction load/store on this MCU, so `volatile`
 * (defeats compiler caching across loop iterations) is enough here
 * without a mutex; not true in general for multi-word shared state. */
static volatile bool s_imu_stationary = false;

/* ---- Core 0 -> Core 1 queue message -------------------------------- */

struct SegDoneMsg {
    const char *seg_id; /* points into TRACK_SEGMENTS' static flash strings */
    char        dir;
    int32_t     d_mm;
    uint16_t    dwell_s;
    int16_t     hdop_x10;
    uint8_t     nsv;
    uint32_t    t; /* unix epoch seconds, from the fix that completed this segment */
    bool        t_is_wall_clock; /* false if t fell back to millis()/1000 -- see
                                   * gnss_matcher_task's now_s comment. Internal
                                   * only, never serialised; guards the Serial-only
                                   * SGT print in handle_seg_done() from rendering
                                   * a bogus 1970 date off a non-epoch value. */
};

static QueueHandle_t s_matcher_queue;

/* ---- SD card store-and-forward (Stage 6 pattern, reused) -----------
 * One fixed directory/file, appended to across every boot -- see the
 * Stage 3/6 harness for why this replaced an earlier per-boot-folder
 * design.
 *
 * gnss_raw.ndjson (Stage 5): every valid GNSS fix, independent of
 * whether the map matcher fires a SEG_DONE -- lets you confirm GNSS
 * acquisition is healthy before trusting/debugging the matcher, since
 * events.ndjson alone stays silent until you're actually on a real
 * track crossing a segment boundary. Written at up to 1 Hz, noticeably
 * more SD I/O than events.ndjson's one-write-per-completed-segment;
 * acceptable for a bring-up/debug harness, flagged in case flash wear
 * matters once this runs for hours unattended. */
#define SD_LOG_DIR      "/lrv_log"
#define SD_LOG_FILE     SD_LOG_DIR "/events.ndjson"
#define SD_RAW_LOG_FILE SD_LOG_DIR "/gnss_raw.ndjson"
static bool s_sd_ready = false;

static void sd_append_line(const char *path, const char *json)
{
    if (!s_sd_ready) {
        return;
    }
    File f = SD.open(path, FILE_APPEND);
    if (!f) {
        Serial.print("[sd FAIL] could not open ");
        Serial.print(path);
        Serial.println(" for append -- continuing without SD log");
        return;
    }
    f.println(json);
    f.close();
}

static void sd_log_json(const char *json)
{
    sd_append_line(SD_LOG_FILE, json);
}

static void sd_log_raw_json(const char *json)
{
    sd_append_line(SD_RAW_LOG_FILE, json);
}

static void sd_init_log_dir()
{
    SPI.begin(SD_SPI_SCLK_PIN, SD_SPI_MISO_PIN, SD_SPI_MOSI_PIN, SD_SPI_CS_PIN);
    if (!SD.begin(SD_SPI_CS_PIN)) {
        Serial.println("[sd FAIL] SD.begin() failed -- card absent or unreadable, continuing without SD logging");
        return;
    }
    if (!SD.exists(SD_LOG_DIR) && !SD.mkdir(SD_LOG_DIR)) {
        Serial.println("[sd FAIL] mkdir failed for " SD_LOG_DIR);
        return;
    }
    s_sd_ready = true;
    Serial.println("[sd] logging to " SD_LOG_FILE " (appending across boots)");
}

/* ---- Modem/GNSS bring-up -- direct AT commands, no TinyGSM --------
 * Explicit user request: no TinyGSM dependency anywhere in this
 * harness. This also sidesteps a real problem -- the publicly
 * published vshymanskyy/TinyGSM package has no SIM7670G modem
 * definition at all (confirmed by inspecting its source directly), so
 * `#define TINY_GSM_MODEM_SIM7670G` only ever worked against LilyGo's
 * own vendored/forked copy, never the registry package PlatformIO
 * actually resolves. */

/* Sends one AT command over SerialAT and reads until a terminal token
 * (OK by default -- pass e.g. "+CGNSSPWR: READY!" to wait for a URC
 * that arrives AFTER the OK), an ERROR line, or timeout. Same read
 * loop GpsOptimisation.ino's own rawGpsQuery() uses for AT+CGNSSINFO
 * -- generalised here so bring-up and the 1 Hz poll share one
 * implementation. */
static bool send_at_command_expect(const char *cmd, String &response,
                                    const char *expect_token,
                                    unsigned long timeout_ms)
{
    response = "";
    while (SerialAT.available()) {
        SerialAT.read();
    }
    SerialAT.println(cmd);

    unsigned long start = millis();
    while (millis() - start < timeout_ms) {
        while (SerialAT.available()) {
            char c = (char)SerialAT.read();
            response += c;
            if (response.indexOf(expect_token) >= 0) {
                return true;
            }
            if (response.indexOf("\r\nERROR\r\n") >= 0) {
                return false;
            }
        }
        delay(1);
    }
    return false;
}

static bool send_at_command(const char *cmd, String &response, unsigned long timeout_ms = 2000)
{
    return send_at_command_expect(cmd, response, "\r\nOK\r\n", timeout_ms);
}

static void pulse_pwrkey()
{
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
    delay(100);
    digitalWrite(BOARD_PWRKEY_PIN, HIGH);
    delay(MODEM_POWERON_PULSE_WIDTH_MS);
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
}

static void wait_for_modem()
{
    String resp;
    int retry = 0;
    while (!send_at_command("AT", resp, 1000)) {
        Serial.print(".");
        if (++retry > 30) {
            Serial.println();
            Serial.println("[modem] retrying PWRKEY pulse...");
            pulse_pwrkey();
            retry = 0;
        }
    }
    Serial.println();
}

/*
 * GNSS mode/enable AT commands: AT+CGNSSPWR=1 powers the GNSS module
 * on, AT+CGNSSMODE=<mode> sets the constellation mix (mode 15 =
 * GPS+GLONASS+GALILEO+BEIDOU, matches MODEM_GPS_MODE) -- both
 * confirmed against SIMCOM's own SIM767XX Series_AT Command
 * Manual_V1.06 (Sec 21.2.1, Sec 21.2.7). AT+CGNSSINFO (the 1 Hz poll)
 * is also manual-confirmed -- gnss_parser.c's field layout matches
 * Sec 21.2.21 exactly.
 *
 * Call order/structure here is ported from GpsOptimisation.ino's own
 * TinyGSM-based bring-up (modem.setGPSMode() once, no retry, THEN a
 * while(!modem.enableGPS()) retry loop) rather than the manual's
 * stated "CGNSSMODE is valid after GNSS power on" -- an earlier
 * version of this function followed the manual instead (CGNSSPWR
 * first, with a longer per-attempt timeout) and still never got a
 * fix, on hardware confirmed to have the antenna on the correct
 * connector, outdoors, clear sky, several minutes. Reordering to
 * match the sketch's proven structure exactly, since that sketch is
 * known-working on this exact board/modem and the manual can't see
 * what TinyGSM's actual (invisible-to-us) fork implementation bundles
 * together internally when the two calls appear in this order at the
 * application level.
 */
static void gnss_bringup()
{
    Serial.println("[modem] starting UART...");
    SerialAT.begin(MODEM_BAUDRATE, SERIAL_8N1, MODEM_RX_PIN, MODEM_TX_PIN);

    pinMode(MODEM_DTR_PIN, OUTPUT);
    digitalWrite(MODEM_DTR_PIN, LOW);
    pinMode(BOARD_PWRKEY_PIN, OUTPUT);
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
    pinMode(BOARD_POWER_SAVE_MODE_PIN, OUTPUT);
    digitalWrite(BOARD_POWER_SAVE_MODE_PIN, HIGH);

    Serial.println("[modem] pulsing PWRKEY...");
    pulse_pwrkey();
    delay(MODEM_START_WAIT_MS);

    Serial.println("[modem] waiting for AT response...");
    wait_for_modem();

    String resp;
    send_at_command("ATI", resp, 3000);
    Serial.print("[modem] ATI: ");
    Serial.println(resp);

    /* modem.setGPSMode(GPS_MODE) in the reference sketch: one call, no
     * retry, no error check -- just fired and moved straight on. */
    char mode_cmd[32];
    snprintf(mode_cmd, sizeof(mode_cmd), "AT+CGNSSMODE=%u", (unsigned)MODEM_GPS_MODE);
    Serial.printf("[gnss] setting GNSS mode %u...\n", (unsigned)MODEM_GPS_MODE);
    if (!send_at_command(mode_cmd, resp, 2000)) {
        Serial.print("[gnss] AT+CGNSSMODE did not return OK, response so far: ");
        Serial.println(resp);
    }

    /* while (!modem.enableGPS(gpio, level)) { ... } in the reference
     * sketch. What that call ACTUALLY sends, verbatim from LilyGo's own
     * TinyGSM fork (LilyGo-Modem-Series lib/TinyGSM/src/
     * TinyGsmClientA76xx.h, enableGPSImpl):
     *
     *   AT+CGDRT=<gpio>,1        modem GPIO direction: output
     *   AT+CGSETV=<gpio>,<level> modem GPIO value: high
     *   AT+CGNSSPWR=1            then wait up to 30 s for the URC
     *                            "+CGNSSPWR: READY!" -- NOT just OK
     *
     * The first two drive the modem's GPIO1, which on this board's
     * schematic is the GNSS_ANT_PWR net: it enables the power rail for
     * the active GNSS antenna. An earlier version of this function sent
     * only AT+CGNSSPWR=1 and accepted the immediate OK -- so the
     * antenna was never powered and the GNSS engine's readiness was
     * never actually awaited, producing endless "no fix" with every
     * command reporting success.
     *
     * Unlike the fork, no blocking wait for the "+CGNSSPWR: READY!"
     * URC here: observed on real hardware (V1.9.05) that the URC
     * doesn't reliably arrive within 30 s even when the engine is fine,
     * and gating on it just stalled the 1 Hz polling loop. Polling
     * AT+CGNSSINFO against a still-booting engine is harmless (the
     * no-fix and error responses are both handled), so the continuous
     * poll IS the retry -- fire the enable commands, log any failures,
     * and let gnss_matcher_task take it from there immediately. */
    Serial.println("[gnss] powering GNSS antenna rail + engine...");
    char gpio_cmd[32];
    snprintf(gpio_cmd, sizeof(gpio_cmd), "AT+CGDRT=%u,1", (unsigned)MODEM_GPS_ENABLE_GPIO);
    if (!send_at_command(gpio_cmd, resp, 2000)) {
        Serial.print("[gnss] AT+CGDRT failed (antenna rail may be unpowered): ");
        Serial.println(resp);
    }
    snprintf(gpio_cmd, sizeof(gpio_cmd), "AT+CGSETV=%u,%u",
             (unsigned)MODEM_GPS_ENABLE_GPIO, (unsigned)MODEM_GPS_ENABLE_LEVEL);
    if (!send_at_command(gpio_cmd, resp, 2000)) {
        Serial.print("[gnss] AT+CGSETV failed (antenna rail may be unpowered): ");
        Serial.println(resp);
    }

    if (send_at_command("AT+CGNSSPWR=1", resp, 10000)) {
        Serial.println("[gnss] power-on accepted, engine booting -- polling starts now.");
    } else {
        Serial.print("[gnss] AT+CGNSSPWR=1 did not return OK, response: ");
        Serial.println(resp);
        Serial.println("[gnss] continuing anyway -- polling will report no fix");
    }

    /* modem.setGPSBaud(115200) in the reference sketch. */
    send_at_command("AT+CGNSSIPR=115200", resp, 2000);
}

/* ---- fixed-point -> human-readable rendering ----------------------
 * The GNSS_RAW JSON below is read by a person off the serial monitor
 * and the SD card, so it carries decimal-formatted values rather than
 * the internal fixed-point integers -- an earlier revision printed
 * lat_e7 raw (12937000), which reads as a correct location "missing
 * its decimal point". Rendered with integer arithmetic rather than
 * %f: exact truncation, no rounding surprises, and no float
 * formatting dragged into the 1 Hz path. */

/* degrees*1e7 -> "[-]D.DDDDDD", truncating the 7th decimal place. The
 * modem emits 6 dp, so the 7th is always a trailing zero from our own
 * scaling and nothing real is lost. */
static void format_deg_e7(int32_t deg_e7, char *out, size_t out_len)
{
    uint32_t mag = (uint32_t)((deg_e7 < 0) ? -(int64_t)deg_e7 : (int64_t)deg_e7);
    snprintf(out, out_len, "%s%lu.%06lu",
             (deg_e7 < 0) ? "-" : "",
             (unsigned long)(mag / 10000000UL),
             (unsigned long)((mag % 10000000UL) / 10UL));
}

/* value*10 -> "[-]D.D" -- altitude in metres, and the three DOPs. */
static void format_x10(int32_t v_x10, char *out, size_t out_len)
{
    uint32_t mag = (uint32_t)((v_x10 < 0) ? -(int64_t)v_x10 : (int64_t)v_x10);
    snprintf(out, out_len, "%s%lu.%lu",
             (v_x10 < 0) ? "-" : "",
             (unsigned long)(mag / 10UL),
             (unsigned long)(mag % 10UL));
}

/* Direct AT+CGNSSINFO query, 1 Hz poll. */
static bool raw_gnss_query(String &response)
{
    return send_at_command("AT+CGNSSINFO", response, RAW_GPS_TIMEOUT_MS);
}

/* ---- Core 0: IMU sampling task (20 Hz, independent of GNSS) -------- */

static void imu_task(void *arg)
{
    (void)arg;

#if IMU_ENABLED
    bool imu_ready = imu_mpu6050_init(QWIIC_I2C_SDA_PIN, QWIIC_I2C_SCL_PIN);
    if (!imu_ready) {
        Serial.println("[imu] disabled: MPU6050 init failed (device not connected/ACKing on the Qwiic port?)");
        vTaskDelete(NULL); /* nothing more for this task to do -- s_imu_stationary stays
                             * false (moving), so gnss_matcher_task just always polls */
    }

    imu_state_t imu_st;
    imu_state_reset(&imu_st);
    bool was_stationary = false;

    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(IMU_SAMPLE_INTERVAL_MS));

        int16_t ax, ay, az;
        if (!imu_mpu6050_read_accel(&ax, &ay, &az)) {
            continue; /* I2C read glitch this tick -- try again next tick */
        }
        bool stationary = imu_state_update(&imu_st, ax, ay, az) != 0;
        s_imu_stationary = stationary;

        if (stationary != was_stationary) {
            Serial.println(stationary
                ? "[imu] stationary -- skipping GNSS polling until motion resumes"
                : "[imu] motion detected -- resuming GNSS polling");
            was_stationary = stationary;
        }
    }
#else
    vTaskDelete(NULL); /* IMU_ENABLED=0 -- s_imu_stationary stays false, GNSS always polls */
#endif
}

/* ---- Core 0: GNSS + matcher task ------------------------------------ */

static void gnss_matcher_task(void *arg)
{
    (void)arg;

    map_matcher_state_t matcher_st;
    map_matcher_init(&matcher_st);

    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(SAMPLE_INTERVAL_MS));

        if (s_imu_stationary) {
            continue; /* imu_task already logged the stationary/motion transition */
        }

        String raw;
        if (!raw_gnss_query(raw)) {
            Serial.println("[gnss] AT+CGNSSINFO timed out/errored, retrying next tick");
            continue;
        }

        gnss_fix_t fix;
        int parse_rc = gnss_parse_cgnssinfo(raw.c_str(), &fix);
        if (parse_rc != 0) {
            Serial.print("[gnss] AT+CGNSSINFO response did not parse (malformed/truncated), raw: [");
            Serial.print(raw);
            Serial.println("]");
            continue;
        }
        if (!fix.valid) {
            Serial.printf("[gnss] no fix yet (fixMode=%u, nsv=%u)\n",
                           (unsigned)fix.fix_mode, (unsigned)fix.nsv);
            continue;
        }

        /* Log/print every valid fix -- independent of whether it moves the
         * matcher -- so GNSS acquisition health is visible/verifiable on
         * its own, before trusting the matcher's SEG_DONE output. */
        uint32_t now_s = (fix.utc_epoch_s != 0) ? fix.utc_epoch_s : (uint32_t)(millis() / 1000);

        char lat_s[16], lon_s[16], alt_s[12];
        char pdop_s[8], hdop_s[8], vdop_s[8];
        char date_s[11], time_s[9];

        format_deg_e7(fix.lat_e7, lat_s, sizeof(lat_s));
        format_deg_e7(fix.lon_e7, lon_s, sizeof(lon_s));
        format_x10(fix.alt_m_x10, alt_s, sizeof(alt_s));
        format_x10(fix.pdop_x10, pdop_s, sizeof(pdop_s));
        format_x10(fix.hdop_x10, hdop_s, sizeof(hdop_s));
        format_x10(fix.vdop_x10, vdop_s, sizeof(vdop_s));

        /* Date/time come from the fix's OWN UTC fields, shifted to SGT.
         * If those didn't parse (utc_epoch_s == 0) emit empty strings
         * rather than a bogus 1970 date -- now_s falls back to millis()
         * for the matcher, but millis() is not a wall clock and must
         * never be rendered as one. */
        if (fix.utc_epoch_s != 0) {
            gnss_format_datetime(fix.utc_epoch_s, GNSS_TZ_OFFSET_S_SINGAPORE,
                                 date_s, sizeof(date_s), time_s, sizeof(time_s));
        } else {
            date_s[0] = '\0';
            time_s[0] = '\0';
        }

        char raw_json[256];
        snprintf(raw_json, sizeof(raw_json),
            "{\"v\":1,\"ev\":\"GNSS_RAW\",\"date\":\"%s\",\"sgt\":\"%s\","
            "\"lat\":%s,\"lon\":%s,\"alt_m\":%s,"
            "\"pdop\":%s,\"hdop\":%s,\"vdop\":%s,\"nsv\":%u}",
            date_s, time_s, lat_s, lon_s, alt_s,
            pdop_s, hdop_s, vdop_s, (unsigned)fix.nsv);
        Serial.println(raw_json);
        sd_log_raw_json(raw_json);

        map_matcher_event_t ev;
        int fired = map_matcher_update(&matcher_st, TRACK_SEGMENTS, TRACK_NUM_SEGMENTS,
                                        &TRACK_NEXT_FWD[0][0], TRACK_NEXT_FWD_COUNT,
                                        fix.lat_e7, fix.lon_e7, now_s, &ev);
        if (!fired) {
            continue;
        }

        SegDoneMsg msg;
        msg.seg_id = ev.seg_id;
        msg.dir = ev.dir;
        msg.d_mm = ev.d_mm;
        msg.dwell_s = ev.dwell_s;
        msg.hdop_x10 = fix.hdop_x10;
        msg.nsv = fix.nsv;
        msg.t = now_s;
        msg.t_is_wall_clock = (fix.utc_epoch_s != 0);

        if (xQueueSend(s_matcher_queue, &msg, 0) != pdTRUE) {
            Serial.println("[matcher] queue full, dropping SEG_DONE");
        }
    }
}

/* ---- Core 1 (Arduino loop): commit-before-publish + Serial/SD log -- */

static void handle_seg_done(const SegDoneMsg &m)
{
    uint32_t new_seq = seq_store_get_seq() + 1;
    int64_t new_odo_m = seq_store_get_odo_m() + (m.d_mm + 500) / 1000; /* mm -> m, half-up */

    if (seq_store_commit(new_seq, new_odo_m) != 0) {
        Serial.println("[commit FAIL] NVS commit failed -- event NOT logged (commit-before-publish)");
        return;
    }

    evt_seg_done_t ev = {};
    ev.lrv_id = MQTT_LRV_ID;
    ev.seq = new_seq;
    ev.t = m.t;
    ev.seg_id = m.seg_id;
    ev.dir = m.dir;
    ev.d_mm = m.d_mm;
    ev.odo_m = new_odo_m;
    ev.hdop_x10 = m.hdop_x10;
    ev.nsv = m.nsv;
    ev.dwell_s = m.dwell_s;

    char json[EVT_JSON_MAX];
    int n = evt_serialize_seg_done(&ev, json, sizeof(json));
    if (n < 0) {
        Serial.println("[serialize FAIL] evt_serialize_seg_done rejected the event");
        return;
    }

    /* Serial-only human-readable SGT stamp, same date/time format and
     * conversion as the GNSS_RAW line -- NOT part of the Tier 1 JSON
     * contract above (that stays frozen, byte-for-byte, for the ingest
     * bridge). Empty if m.t was a millis() fallback rather than a real
     * epoch (m.t_is_wall_clock == false) -- never render a fallback
     * clock value as if it were a wall-clock date. */
    char date_s[11], time_s[9];
    if (m.t_is_wall_clock) {
        gnss_format_datetime(m.t, GNSS_TZ_OFFSET_S_SINGAPORE, date_s, sizeof(date_s), time_s, sizeof(time_s));
    } else {
        date_s[0] = '\0';
        time_s[0] = '\0';
    }
    Serial.printf("{\"date\":\"%s\",\"sgt\":\"%s\"}\n", date_s, time_s);

    Serial.println(json);
    sd_log_json(json);
}

void setup()
{
    Serial.begin(115200);
    /* Native USB-CDC serial re-enumerates on reset/power-cycle. Serial's
     * own "connected" flag isn't a fully reliable signal for "a monitor
     * has actually attached" across ESP32 Arduino core versions/host
     * OSes -- keep the bounded wait as a fast path, but also repeat the
     * boot line for a few seconds so a monitor attaching anywhere in
     * that window still catches it (see the Stage 6 harness for the
     * fuller explanation). */
    unsigned long serial_wait_start = millis();
    while (!Serial && millis() - serial_wait_start < 3000) {
        delay(10);
    }
    delay(100);

    seq_store_init();
    sd_init_log_dir();

    char boot_banner[80];
    snprintf(boot_banner, sizeof(boot_banner), "[boot] resumed seq=%lu, sd=%s",
             (unsigned long)seq_store_get_seq(), s_sd_ready ? "ok" : "FAILED");
    for (int i = 0; i < 5; i++) {
        Serial.println(boot_banner);
        delay(600);
    }

    gnss_bringup();

    s_matcher_queue = xQueueCreate(8, sizeof(SegDoneMsg));

    xTaskCreatePinnedToCore(imu_task, "imu", 4096, nullptr, 1, nullptr, 0 /* Core 0 */);
    xTaskCreatePinnedToCore(gnss_matcher_task, "gnss_matcher", 8192, nullptr, 1, nullptr, 0 /* Core 0 */);
}

void loop()
{
    SegDoneMsg msg;
    if (xQueueReceive(s_matcher_queue, &msg, 0) == pdTRUE) {
        handle_seg_done(msg);
    }
    delay(20);
}
