/*
 * Stage 5 -- real GNSS (direct AT commands) + map matcher + optional
 * IMU stationary gate (Build Plan Sec 5 / TDD Sec 5.3-5.5).
 *
 * Serial + SD only in this harness -- no Wi-Fi/MQTT. Deferred per
 * explicit user instruction until a SIM card is available to test
 * cellular + MQTT together (Stage 7). Reuses Stage 6's SD
 * store-and-forward pattern: one fixed /lrv_log/ directory, appended
 * to across every boot (not a fresh folder per boot -- that was an
 * earlier design, dropped after it grew unboundedly across routine
 * test resets with no benefit).
 *
 * Core 0: gnss_matcher_task -- once per second: if IMU_ENABLED and the
 *         IMU classifies the vehicle stationary, skip the GNSS poll
 *         entirely (saves modem cycles/power); otherwise issue a raw
 *         AT+CGNSSINFO query (direct AT command, not TinyGSM's parsed
 *         GPS helpers -- explicit user request), parse it, and feed the
 *         fix into the map matcher. Every valid fix is printed/logged
 *         to gnss_raw.ndjson on its own -- independent of the matcher --
 *         so GNSS acquisition can be verified before trusting matcher
 *         output. A completed segment additionally goes on the queue
 *         for Core 1.
 * Core 1 (Arduino loop()): commit-before-publish (seq_store), Serial +
 *         SD logging of completed segments (events.ndjson), queue
 *         draining. No network I/O.
 *
 * Modem/GPS bring-up (PWRKEY pulse, DTR, power-save pin, setGPSMode,
 * enableGPS) is ported from the team's own working reference sketch
 * for this exact board/modem (GpsOptimisation.ino) via TinyGSM, since
 * that bring-up sequence is already hardware-proven -- only the 1 Hz
 * position query itself uses a direct raw AT command, per the user's
 * explicit request, matching that same reference sketch's own
 * rawGpsQuery() approach.
 *
 * Known simplifications (flagged, not silent):
 *   - dir ('E'/'W') is a Stage 5 placeholder for forward/reverse
 *     traversal, not a real cardinal direction -- see map_matcher.h.
 *   - firmware/src/track_data.h must be generated by the user via
 *     tools/track_pipeline.py from a real track.geojson before this
 *     env will compile (Build Plan Sec 4 / README) -- it is
 *     intentionally not committed as a placeholder here.
 */
#include <Arduino.h>
#include <Wire.h>

#define TINY_GSM_MODEM_SIM7670G
#define TINY_GSM_RX_BUFFER 1024
#include <TinyGsmClient.h>

extern "C" {
#include "event_serializer.h"
#include "seq_store.h"
#include "gnss_parser.h"
#include "map_matcher.h"
#include "imu_state.h"
#include "imu_mpu6050.h"
}

#include <SPI.h>
#include <SD.h>

#include "../../config.h"
#include "../../pins_board.h"
#include "track_data.h" /* TRACK_SEGMENTS, TRACK_NUM_SEGMENTS, TRACK_NEXT_FWD(_COUNT) --
                          * generated by tools/track_pipeline.py, see header comment above */

#define SerialAT Serial1
#define SAMPLE_INTERVAL_MS 1000UL /* 1 Hz, TDD */
#define RAW_GPS_TIMEOUT_MS 800UL

TinyGsm modem(SerialAT);

/* ---- Core 0 -> Core 1 queue message -------------------------------- */

struct SegDoneMsg {
    const char *seg_id; /* points into TRACK_SEGMENTS' static flash strings */
    char        dir;
    int32_t     d_mm;
    uint16_t    dwell_s;
    int16_t     hdop_x10;
    uint8_t     nsv;
    uint32_t    t; /* unix epoch seconds, from the fix that completed this segment */
};

static QueueHandle_t s_matcher_queue;

/* ---- SD card store-and-forward (Stage 6 pattern, reused) -----------
 * One fixed directory/file, appended to across every boot -- see the
 * Stage 3/6 harness for why this replaced an earlier per-boot-folder
 * design.
 *
 * gnss_raw.ndjson (Stage 5): every valid GNSS fix, independent of
 * whether the map matcher fires a SEG_DONE -- lets you confirm GNSS
 * acquisition is healthy before trusting/debugging the matcher, since
 * events.ndjson alone stays silent until you're actually on a real
 * track crossing a segment boundary. Written at up to 1 Hz, noticeably
 * more SD I/O than events.ndjson's one-write-per-completed-segment;
 * acceptable for a bring-up/debug harness, flagged in case flash wear
 * matters once this runs for hours unattended. */
#define SD_LOG_DIR      "/lrv_log"
#define SD_LOG_FILE     SD_LOG_DIR "/events.ndjson"
#define SD_RAW_LOG_FILE SD_LOG_DIR "/gnss_raw.ndjson"
static bool s_sd_ready = false;

static void sd_append_line(const char *path, const char *json)
{
    if (!s_sd_ready) {
        return;
    }
    File f = SD.open(path, FILE_APPEND);
    if (!f) {
        Serial.print("[sd FAIL] could not open ");
        Serial.print(path);
        Serial.println(" for append -- continuing without SD log");
        return;
    }
    f.println(json);
    f.close();
}

static void sd_log_json(const char *json)
{
    sd_append_line(SD_LOG_FILE, json);
}

static void sd_log_raw_json(const char *json)
{
    sd_append_line(SD_RAW_LOG_FILE, json);
}

static void sd_init_log_dir()
{
    SPI.begin(SD_SPI_SCLK_PIN, SD_SPI_MISO_PIN, SD_SPI_MOSI_PIN, SD_SPI_CS_PIN);
    if (!SD.begin(SD_SPI_CS_PIN)) {
        Serial.println("[sd FAIL] SD.begin() failed -- card absent or unreadable, continuing without SD logging");
        return;
    }
    if (!SD.exists(SD_LOG_DIR) && !SD.mkdir(SD_LOG_DIR)) {
        Serial.println("[sd FAIL] mkdir failed for " SD_LOG_DIR);
        return;
    }
    s_sd_ready = true;
    Serial.println("[sd] logging to " SD_LOG_FILE " (appending across boots)");
}

/* ---- Modem/GNSS bring-up, ported from GpsOptimisation.ino ---------- */

static void pulse_pwrkey()
{
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
    delay(100);
    digitalWrite(BOARD_PWRKEY_PIN, HIGH);
    delay(MODEM_POWERON_PULSE_WIDTH_MS);
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
}

static void wait_for_modem()
{
    int retry = 0;
    while (!modem.testAT(1000)) {
        Serial.print(".");
        if (++retry > 30) {
            Serial.println();
            Serial.println("[modem] retrying PWRKEY pulse...");
            pulse_pwrkey();
            retry = 0;
        }
    }
    Serial.println();
}

static void gnss_bringup()
{
    Serial.println("[modem] starting UART...");
    SerialAT.begin(MODEM_BAUDRATE, SERIAL_8N1, MODEM_RX_PIN, MODEM_TX_PIN);

    pinMode(MODEM_DTR_PIN, OUTPUT);
    digitalWrite(MODEM_DTR_PIN, LOW);
    pinMode(BOARD_PWRKEY_PIN, OUTPUT);
    digitalWrite(BOARD_PWRKEY_PIN, LOW);
    pinMode(BOARD_POWER_SAVE_MODE_PIN, OUTPUT);
    digitalWrite(BOARD_POWER_SAVE_MODE_PIN, HIGH);

    Serial.println("[modem] pulsing PWRKEY...");
    pulse_pwrkey();
    delay(MODEM_START_WAIT_MS);

    Serial.println("[modem] waiting for AT response...");
    wait_for_modem();
    Serial.print("[modem] detected: ");
    Serial.println(modem.getModemName());

    Serial.printf("[gnss] setting GPS mode %u...\n", (unsigned)MODEM_GPS_MODE);
    modem.setGPSMode(MODEM_GPS_MODE);

    Serial.println("[gnss] enabling GPS...");
    while (!modem.enableGPS(MODEM_GPS_ENABLE_GPIO, MODEM_GPS_ENABLE_LEVEL)) {
        Serial.print(".");
        delay(500);
    }
    Serial.println();
    Serial.println("[gnss] enabled.");
}

/* Direct AT+CGNSSINFO query (Stage 5: explicit user request for direct
 * AT commands over the polling path, unlike modem bring-up above). */
static bool raw_gnss_query(String &response)
{
    response = "";
    while (SerialAT.available()) {
        SerialAT.read();
    }
    SerialAT.println("AT+CGNSSINFO");

    unsigned long start = millis();
    while (millis() - start < RAW_GPS_TIMEOUT_MS) {
        while (SerialAT.available()) {
            char c = (char)SerialAT.read();
            response += c;
            if (response.indexOf("\r\nOK\r\n") >= 0) {
                return true;
            }
            if (response.indexOf("\r\nERROR\r\n") >= 0) {
                return false;
            }
        }
        delay(1);
    }
    return false;
}

/* ---- Core 0: GNSS + matcher task ------------------------------------ */

static void gnss_matcher_task(void *arg)
{
    (void)arg;

    map_matcher_state_t matcher_st;
    map_matcher_init(&matcher_st);

    imu_state_t imu_st;
    imu_state_reset(&imu_st);
    bool imu_ready = false;
#if IMU_ENABLED
    imu_ready = imu_mpu6050_init(QWIIC_I2C_SDA_PIN, QWIIC_I2C_SCL_PIN);
    if (!imu_ready) {
        Serial.println("[imu] disabled: MPU6050 init failed (device not connected/ACKing on the Qwiic port?)");
    }
#endif
    bool was_stationary = false;

    for (;;) {
        vTaskDelay(pdMS_TO_TICKS(SAMPLE_INTERVAL_MS));

        bool stationary = false;
        if (imu_ready) {
            int16_t ax, ay, az;
            if (imu_mpu6050_read_accel(&ax, &ay, &az)) {
                stationary = imu_state_update(&imu_st, ax, ay, az) != 0;
            }
        }
        if (stationary != was_stationary) {
            Serial.println(stationary
                ? "[imu] stationary -- skipping GNSS polling until motion resumes"
                : "[imu] motion detected -- resuming GNSS polling");
            was_stationary = stationary;
        }
        if (stationary) {
            continue;
        }

        String raw;
        if (!raw_gnss_query(raw)) {
            Serial.println("[gnss] AT+CGNSSINFO timed out/errored, retrying next tick");
            continue;
        }

        gnss_fix_t fix;
        int parse_rc = gnss_parse_cgnssinfo(raw.c_str(), &fix);
        if (parse_rc != 0) {
            Serial.println("[gnss] AT+CGNSSINFO response did not parse (malformed/truncated)");
            continue;
        }
        if (!fix.valid) {
            Serial.printf("[gnss] no fix yet (fixMode=%u, nsv=%u)\n",
                           (unsigned)fix.fix_mode, (unsigned)fix.nsv);
            continue;
        }

        /* Log/print every valid fix -- independent of whether it moves the
         * matcher -- so GNSS acquisition health is visible/verifiable on
         * its own, before trusting the matcher's SEG_DONE output. */
        uint32_t now_s = (fix.utc_epoch_s != 0) ? fix.utc_epoch_s : (uint32_t)(millis() / 1000);
        char raw_json[160];
        snprintf(raw_json, sizeof(raw_json),
            "{\"v\":1,\"ev\":\"GNSS_RAW\",\"t\":%lu,\"lat_e7\":%ld,\"lon_e7\":%ld,"
            "\"hdop_x10\":%d,\"nsv\":%u,\"speed_mmps\":%lu}",
            (unsigned long)now_s, (long)fix.lat_e7, (long)fix.lon_e7,
            (int)fix.hdop_x10, (unsigned)fix.nsv, (unsigned long)fix.speed_mmps);
        Serial.println(raw_json);
        sd_log_raw_json(raw_json);

        map_matcher_event_t ev;
        int fired = map_matcher_update(&matcher_st, TRACK_SEGMENTS, TRACK_NUM_SEGMENTS,
                                        &TRACK_NEXT_FWD[0][0], TRACK_NEXT_FWD_COUNT,
                                        fix.lat_e7, fix.lon_e7, now_s, &ev);
        if (!fired) {
            continue;
        }

        SegDoneMsg msg;
        msg.seg_id = ev.seg_id;
        msg.dir = ev.dir;
        msg.d_mm = ev.d_mm;
        msg.dwell_s = ev.dwell_s;
        msg.hdop_x10 = fix.hdop_x10;
        msg.nsv = fix.nsv;
        msg.t = now_s;

        if (xQueueSend(s_matcher_queue, &msg, 0) != pdTRUE) {
            Serial.println("[matcher] queue full, dropping SEG_DONE");
        }
    }
}

/* ---- Core 1 (Arduino loop): commit-before-publish + Serial/SD log -- */

static void handle_seg_done(const SegDoneMsg &m)
{
    uint32_t new_seq = seq_store_get_seq() + 1;
    int64_t new_odo_m = seq_store_get_odo_m() + (m.d_mm + 500) / 1000; /* mm -> m, half-up */

    if (seq_store_commit(new_seq, new_odo_m) != 0) {
        Serial.println("[commit FAIL] NVS commit failed -- event NOT logged (commit-before-publish)");
        return;
    }

    evt_seg_done_t ev = {};
    ev.lrv_id = MQTT_LRV_ID;
    ev.seq = new_seq;
    ev.t = m.t;
    ev.seg_id = m.seg_id;
    ev.dir = m.dir;
    ev.d_mm = m.d_mm;
    ev.odo_m = new_odo_m;
    ev.hdop_x10 = m.hdop_x10;
    ev.nsv = m.nsv;
    ev.dwell_s = m.dwell_s;

    char json[EVT_JSON_MAX];
    int n = evt_serialize_seg_done(&ev, json, sizeof(json));
    if (n < 0) {
        Serial.println("[serialize FAIL] evt_serialize_seg_done rejected the event");
        return;
    }

    Serial.println(json);
    sd_log_json(json);
}

void setup()
{
    Serial.begin(115200);
    /* Native USB-CDC serial re-enumerates on reset/power-cycle. Serial's
     * own "connected" flag isn't a fully reliable signal for "a monitor
     * has actually attached" across ESP32 Arduino core versions/host
     * OSes -- keep the bounded wait as a fast path, but also repeat the
     * boot line for a few seconds so a monitor attaching anywhere in
     * that window still catches it (see the Stage 6 harness for the
     * fuller explanation). */
    unsigned long serial_wait_start = millis();
    while (!Serial && millis() - serial_wait_start < 3000) {
        delay(10);
    }
    delay(100);

    seq_store_init();
    sd_init_log_dir();

    char boot_banner[80];
    snprintf(boot_banner, sizeof(boot_banner), "[boot] resumed seq=%lu, sd=%s",
             (unsigned long)seq_store_get_seq(), s_sd_ready ? "ok" : "FAILED");
    for (int i = 0; i < 5; i++) {
        Serial.println(boot_banner);
        delay(600);
    }

    gnss_bringup();

    s_matcher_queue = xQueueCreate(8, sizeof(SegDoneMsg));

    xTaskCreatePinnedToCore(gnss_matcher_task, "gnss_matcher", 8192, nullptr, 1, nullptr, 0 /* Core 0 */);
}

void loop()
{
    SegDoneMsg msg;
    if (xQueueReceive(s_matcher_queue, &msg, 0) == pdTRUE) {
        handle_seg_done(msg);
    }
    delay(20);
}
